name: ninarith-deployer
on: push
jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: Ninareth

      - name: Checkout website repo
        uses: actions/checkout@v3
        with:
          repository: csb324/eleventy-obsidian-ninareth
          path: main
      
      - name: Commit new content to website repo
        run: npm run deploy
        working-directory: main
