name: ninarith-deployer
on: push
jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: Ninareth

      - name: Checkout website repo
        uses: actions/checkout@v3
        with:
          repository: csb324/eleventy-obsidian-ninareth
          path: main
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      
      - name: Install npm dependencies
        run: npm install
        working-directory: main
        
      - name: Commit new content to website repo
        env:
          GITHUB_TOKEN: ${{ secrets.OBSIDIAN_PAT }}
          GIT_CMD_REPOSITORY="https://${{DESTINATION_REPOSITORY_USERNAME}}:${{API_TOKEN_GITHUB}}@${{GITHUB_SERVER}}/${{DESTINATION_REPOSITORY_USERNAME}}/${{DESTINATION_REPOSITORY_NAME}}.git"
        run: |
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          touch version.txt
          git commit --allow-empty -m "arbitrary-commit"
          git push
        working-directory: main
      