name: ninarith-deployer
on: push
jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout website repo
        uses: actions/checkout@v3
        with:
          repository: csb324/eleventy-obsidian-ninareth
          path: Ninareth
      
      - name: tell me some facts i guess
        run: ls -la
